.PU
.TH PRBOOM 6 local
.SH NAME
prboom \- PrBoom, a version of Doom for Unix, Linux and Windows systems
.SH SYNOPSIS
.ll +8
.B prboom
[ \-complevel \fIlvl\fR ]
.BR
[ \-width \fIw\fR ] [ \-height \fIh\fR ]
.BR
[ \-iwad \fIiwadname\fR ] [ -file \fIwad1 \&...\fR ] [ \-deh \fIdeh_file\fR ] [ \-noload ]
.BR
[ \-loadgame {0,1,2,3,4,5,6,7} ] [ \-warp { \fImap\fR | \fIepis level\fR } \-skill {1,2,3,4,5} ]
.BR
[ {\-fastdemo,\-timedemo,\-playdemo} \fIdemofile\fR [ \-ffmap \fInum\fR ] ] [ \-record \fIdemofile\fR ] 
.BR
[ \-net \fIhostname\fR[:\fIport\fR] ]
[ \-deathmatch [ \-altdeath ] ] [ { \-timer \fImins\fR | \-avg } ] ]
.BR
[ \-nosound ] [ \-nosfx ] [ \-nomusic ] [ \-nojoy ] [ \-grabmouse ]
[ \-noaccel ] [ \-{1,2,3} ]
.BR
[ \-config \fImyconf\fR ] [ \-save \fIsavedir\fR ] 
.BR
[ \-bexout \fIbexdbg\fR ] [ \-debugfile \fIdebug_file\fR ] [ \-devparm ] [ \-noblit ] [ \-nodrawers ]
.SH DESCRIPTION
.B PrBoom
is a version of the 3D shoot'em'up Doom, originally by iD software. 
It is based on Boom, a version of Doom adapted by TeamTNT 
(http://www.teamtnt.com) for DOS. PrBoom uses the SDL library, 
meaning it can run on a variety of different systems, 
including Windows, X11, Linux/SVGALib.
.SH Options
.TP
\-complevel \fIlvl\fR
This sets the compatibility mode that PrBoom runs in. If you need to change
this, see README.compat.

.SH Video Options
.TP
\-width \fIw\fR
Specifies the width of the PrBoom window, in pixels. Default is 320, the
width must be greater than 320..
.TP
\-height \fIh\fR
Specifies the height of the PrBoom window, in pixels. Default is 200, the
height must be greater than 200.
.SH WAD Options
.TP
\-iwad \fIiwadname\fR
Specifies the location of the IWAD file, typically doom.wad or doom2.wad (or
doom2f.wad). This tells prboom where the main .wad file that came with the
version of Doom that you own is. 
.TP
\-file \fIwad1 \&...\fR
Specifies a list of PWAD files to load in addition to the IWAD file. PWAD
files modify the existing Doom game, by adding levels or new sounds or
graphics. PWAD files are widely available for download; try
ftp.cdrom.com/pub/idgames for starters.
.TP
\-deh \fIdeh_file\fR
Tells PrBoom to load the dehacked patch \fIdeh_file\fR.
.SH Game Options
.TP
\-loadgame {0,1,2,3,4,5,6,7}
Instructs PrBoom to load the specified saved game immediately. 
.TP
\-warp { \fImap\fR | \fIepis\fR \fIlevel\fR }
Tells PrBoom to begin a new game immediately. For Doom 1 or Ultimate Doom,
you must specify the \fIepis\fRode and \fIlevel\fR number to begin at
(\fIepis\fR is 1 for Knee-Deep in the Dead, 2 for Shores of Hell, 3 for
Inferno, 4 for Ultimate Doom; \fIlevel\fR is between 1 and 9). For Doom ][ or
Final Doom, you must specify the \fImap\fR to begin at, which is between 1 and
32 (30 for German Doom ][).
.TP
\-skill \fIn\fR
Tells PrBoom to begin the game
at skill level \fIn\fR (1 for ITYTD, 2 for Not Too Rough, 3 for Hurt Me
Plenty, 4 for Ultraviolent, 5 for Nightmare). 
.TP
\-respawn Tells PrBoom that
monsters that die should respawn (come back to life) after a while. Not for
the inexperienced.
.TP
\-fast
Tells PrBoom to make all the monsters move \&
react faster. Not for the inexperienced. 
.TP
\-nomonsters
Tells PrBoom to include no monsters in the game.
.SH Multiplayer Options
.TP
\-net \fIhostname\fR[:\fIport\fR]
Specifies that a TCP/IP network game is to be started. \fIhostname\fR is the 
name of the machine on which the network game server is running 
(prboom-game-server). For more information about this, see 
prboom-game-server(6) and the README that came with prboom. \fIport\fR is the 
port number on the remote machine to which to connect; if not specified, the 
default of 5030 (which is the default for prboom-game-server(6)) is assumed. 
The server will configure your PrBoom settings, so that all tha players have 
the same game settings (skill, map etc). 
.PP
Also, the server may specify additional PWAD files to play with; if you do 
not have the required .WAD file, PrBoom will ask the server for a download 
path, and attempt to use wget(1) and if necessary unzip(1) to download 
and extract the required WAD.
.TP
\-port \fIportnum\fR
Specifies the local port to use to communicate with the server in a netgame.
.TP
\-deathmatch
No longer used. Tells PrBoom to begin a deathmatch game, but this is overridden 
by the server's settings. Only works for single play (!).
.TP
\-altdeath
Similar to \-deathmatch, but implies a different set of rules for the 
deathmatch game. No longer used (specified by the server).
.TP
\-timer \fImins\fR
No longer used. Specifies that levels will end after \fImins\fR minutes of
play if the level is still being played, but is overridden by the server in 
a netgame. Not really useful for single play.
.TP
\-avg
Equivalent to -timer 20
.SH Demo (LMP) Options
.TP
\-record \fIdemofile\fR
Instructs PrBoom to begin recording a demo, to be stored in \fIdemofile\fR.lmp. You should specify \fBgame options\fR to specify which level and skill to record at.
.TP
\-playdemo \fIdemofile\fR
Play the recorded demo \fIdemofile\fR.lmp
.TP
\-timedemo \fIdemofile\fR
Play the recorded demo \fIdemofile\fR.lmp, reporting information about the length of the demo (in gametics) afterwards.
.TP
\-fastdemo \fIdemofile\fR
Play the recorded demo \fIdemofile\fR.lmp as fast as possible. Useful for 
benchmarking PrBoom, as compared to other versions of Doom.
.TP
\-ffmap \fInum\fR
Fast forward the demo (play at max speed) until reaching map \fInum\fR
(note that this takes just a number, not a map name, so so -ffmap 7 to go fast
until MAP07 or ExM7).
.SH I/O Options
.TP
\-nosound
Disables all sound effects and in-game music. This prevents the sound server 
loading, which lets the game run a little faster. 
.TP
\-nosfx
Disables sound effects during the game. This does not stop the sound server 
loading, however, so for best performance use -nosound.
.TP
\-nomusic
Disables playing of music in the game.
.TP
\-nojoy
Disables joystick support.
.TP
\-noaccel
For prboom, this prevents it using the MITShm server extension for passing
the screen data to the X server. This option may be required if the X server
is not local. For lsdoom, this tells lsdoom not to use the accelerated
graphics functions that SVGALib provides even when they are supported for
your video card (normally this is autodetected).
.TP
\-{1,2,3}
Specifies the scale factor by which to enlarge the window. The default, -1, 
displays the normal 320x200 pixel Doom screen (or whatever size is specified by 
the -width and -height parameters or in the config file for prboom). 
If this window is too small, try using -2 or -3 to enlarge the window.
.SH Configuration
.TP
\-config \fImyconf\fR
Loads an alternative configuration file, named \fImyconf\fR. The default is 
boom.cfg, taken from the same directory as PrBoom was run from.
.TP
\-save \fIsavedir\fR
Causes prboom to save games in the directory specified by \fIsavedir\fR 
instead of ~/.prboom/.
.SH Debugging/Profiling Options
.TP
\-devparm
Development mode. This used to be required for many things, but is almost redundant now. It's only significant effect (to my knowledge) is to show a series of white dots in the lower left corner of the prboom window. The current frame rate is (I think) 35 / (number of dots).
.TP
\-debugfile \fIdebug_file\fR
Causes some debugging information, mainly network info I believe, to be written to the named file as prboom runs.
.TP
\-nodrawers
Causes no rendering to be done. The only conceivable use of this is (a) a multiplayer server (b) to test the speed of the other routines in the program, when combined with -timedemo.
.TP
\-noblit
Causes no copying to the screen from the rendering buffer to be performed. The only conceivable use of this is (a) a multiplayer server (b) to test the speed of the other routines in the program, when combined with -timedemo.
.TP
\-bexout \fIbexdbg\fR
Causes diagnostics related to bex and dehacked file processing to be written 
to the names file.
.SH More Information
wget(1), unzip(1), boom.cfg(5), prboom-game-server(6)
.PP
For more information, see the README that came with PrBoom, the Boom 
documentation, and your original Doom documentation.
.PP
Doom is a registered trademark of id software (http://www.idsoftware.com).
.SH Author
See the file AUTHORS included with the PrBoom distribution.
