#!/bin/sh
#
# $Id: maintainer-build,v 1.1 2000/09/20 09:26:19 figgi Exp $
# cphipps - short script to start building from a maintainer-clean'ed tree
#
aclocal && autoheader && automake --include-deps && autoconf
