;------------------------------------------------------------------------
;test.WAD breakdown, written by BRK.EXE on 02:50 PM Sunday Oct 24, 1999
;------------------------------------------------------------------------
;

; Resource section for LUMPS, default location: LUMPS\*.LMP
[LUMPS]
PRBOOM
COLCHIP
CURCHIP
VRFYBOX

; No DEFINITIONS in test.WAD
; No LEVELS in test.WAD
; No TEXTURES in test.WAD
; No SOUNDS in test.WAD
; No WAVESNDS in test.WAD
; No MUSICS in test.WAD
; No GRAPHICS in test.WAD
; No COLMAPS in test.WAD
; No TRANMAPS in test.WAD
; No SPRITES in test.WAD
; No PATCHES in test.WAD
; No FLATS in test.WAD

; Resource section for HISTORY, default location: HISTORY\*.TXT
[HISTORY]
HISTORY

