# PrBoom Dreamcast
#
# src/dc/Makefile.dc
# (c)2001 Florian Schulze
#   

all: libdcdoom.a

include $(KOS_BASE)/Makefile.rules

OBJS = i_system.o i_sound.o

#KOS_CFLAGS += -I. -I../. -I../../. -nostdlib -DHAVE_CONFIG_H -DDREAMCAST --fast-math -O0
KOS_CFLAGS += -I. -I../. -I../../. -DHAVE_CONFIG_H -DDREAMCAST

libdcdoom.a: $(OBJS)
	$(KOS_AR) rcs libdcdoom.a $(OBJS)

clean:
	-rm -f *.o *.klf libdcdoom.a
