# PrBoom Dreamcast
#
# Makefile.dc
# (c)2001 Florian Schulze
#   

all:
	-ln -s src/dc/config.h config.h >nul
	$(MAKE) -C src -f makefile.dc
	-cp src/prboom.elf prboom.elf
	-sh-elf-strip -g prboom.elf

run: all
	-dc-tool -x prboom.elf

clean:
	$(MAKE) -C src -f makefile.dc clean
	-rm -f prboom.elf
	-rm -f config.h
