#define IDI_ICON1                       101
#define IDI_ICON2                       102
#define IDI_ICON3                       103
#define IDI_ICON4                       104
#define IDI_ICON5                       105
#define IDI_ICON6                       106
#define IDD_LAUNCHERSERVERDIALOG        120
#define IDD_LAUNCHERCLIENTDIALOG        121
#define IDC_TAB1                        1003
#define IDC_COMBO1                      1004
#define IDC_IWADCOMBO                   1004
#define IDC_IWADLIST                    1006
#define IDC_LIST2                       1006
#define IDC_PWADLIST                    1006
#define IDC_LIST3                       1007
#define IDC_COMMANDCOMBO                1008
#define IDC_HISTORYCOMBO                1009
#define IDC_EDIT2                       1014
#define IDC_CHECK1                      1015
#define IDC_FULLFILENAMESTATIC          1016
